name: Cross Repo Tests

on: [push, pull_request]

jobs:
  manageiq:
    uses: agrare/manageiq-cross_repo/.github/workflows/manageiq_cross_repo.yaml@github_actions
    with:
      test_repo: ManageIQ/manageiq@master
      repos: ManageIQ/manageiq@master
